[package]
name = "plonk_circuit_compiler"
version = "0.1.0"
edition = "2024"

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.20.2"

[dependencies]
lalrpop-util = { version = "0.20.2", features = ["lexer", "unicode"] }
